questions = [
    "What is the capital of France?",
    "Who wrote 'To Kill a Mockingbird'?",
    "What is the chemical symbol for water?",
    "What is the tallest mammal?",
    "What is the largest organ in the human body?",
    "Which planet is known as the Red Planet?",
    "Who painted the Mona Lisa?",
    "What is the currency of Japan?",
    "What year did World War II end?",
    "What is the main ingredient in guacamole?",
    "Who developed the theory of relativity?",
    "What is the smallest country in the world?",
    "What is the process by which plants make their own food called?",
    "What is the closest star to Earth?",
    "Who wrote 'Romeo and Juliet'?",
    "What is the chemical symbol for gold?",
    "What is the longest river in the world?",
    "What is the study of Earth's physical structure and substance called?",
    "What is the largest planet in our solar system?",
    "What is the national flower of Japan?",
    "Who painted 'Starry Night'?",
    "What is the currency of China?",
    "What is the chemical symbol for iron?",
    "What is the fastest land animal?",
    "What is the primary ingredient in hummus?",
    "Who invented the telephone?",
    "Which ocean is the largest?",
    "Who wrote '1984'?",
    "What is the chemical symbol for sodium?",
    "What is the deepest ocean on Earth?",
    "Who was the first woman to win a Nobel Prize?",
    "What is the most abundant gas in Earth's atmosphere?",
    "What is the largest desert in the world?",
    "Who painted 'The Persistence of Memory'?",
    "What is the currency of Russia?",
    "What is the chemical symbol for silver?",
    "What is the hardest natural substance on Earth?",
    "Who discovered penicillin?",
    "What is the smallest bone in the human body?",
    "What is the boiling point of water in Fahrenheit?"
]

answers = [
    "Paris",
    "Harper Lee",
    "H2O",
    "Giraffe",
    "Skin",
    "Mars",
    "Leonardo da Vinci",
    "Yen",
    "1945",
    "Avocado",
    "Albert Einstein",
    "Vatican City",
    "Photosynthesis",
    "Sun",
    "William Shakespeare",
    "Au",
    "Nile",
    "Geology",
    "Jupiter",
    "Cherry blossom",
    "Vincent van Gogh",
    "Yuan",
    "Fe",
    "Cheetah",
    "Chickpeas",
    "Alexander Graham Bell",
    "Pacific Ocean",
    "George Orwell",
    "Na",
    "Pacific Ocean",
    "Marie Curie",
    "Nitrogen",
    "Sahara",
    "Salvador Dali",
    "Russian Ruble",
    "Ag",
    "Diamond",
    "Alexander Fleming",
    "Stapes",
    "212°F"
]
